'use client';

import Link from 'next/link';
import { CheckCircle2, Circle, Play, Video } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

type Lesson = { id: string; title: string; description: string | null; vimeo_video_id: string | null; vdocipher_video_id: string | null; lesson_order: number; duration_seconds: number | null };

export default function LessonPlayer({ course, lessons, completedLessonIds }: { course: { title: string; description: string | null; level: string }; lessons: Lesson[]; completedLessonIds: string[] }) {
  const [activeLessonId, setActiveLessonId] = useState(lessons[0]?.id ?? ''); const [completed, setCompleted] = useState(new Set(completedLessonIds)); const [saving, setSaving] = useState(false); const [playerUrl, setPlayerUrl] = useState(''); const router = useRouter();
  const lesson = lessons.find((item) => item.id === activeLessonId);
  useEffect(() => { let cancelled = false; setPlayerUrl(''); if (!lesson?.vdocipher_video_id) return; fetch('/api/vdocipher/otp', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ videoId: lesson.vdocipher_video_id }) }).then((response) => response.json()).then((data: { otp?: string; playbackInfo?: string }) => { if (!cancelled && data.otp && data.playbackInfo) setPlayerUrl(`https://player.vdocipher.com/v2/?otp=${data.otp}&playbackInfo=${data.playbackInfo}`); }).catch(() => undefined); return () => { cancelled = true; }; }, [lesson]);
  async function completeLesson() { if (!lesson) return; setSaving(true); const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (user) { await supabase.from('student_progress').upsert({ student_id: user.id, lesson_id: lesson.id, completed: true, watched_seconds: lesson.duration_seconds ?? 0 }, { onConflict: 'student_id,lesson_id' }); setCompleted((current) => new Set([...current, lesson.id])); router.refresh(); } setSaving(false); }
  if (!lesson) return <main className="grid min-h-screen place-items-center bg-[#07111f] text-white"><p>No lessons have been added to this course yet.</p></main>;
  return <main className="min-h-screen bg-[#07111f] text-white"><header className="border-b border-white/10 px-6 py-5"><div className="mx-auto flex max-w-7xl items-center justify-between"><Link href="/dashboard" className="text-sm text-amber-400">← Dashboard</Link><span className="text-sm text-slate-400">{course.level}</span></div></header><div className="mx-auto grid max-w-7xl gap-8 px-6 py-10 lg:grid-cols-[1fr_340px]"><section><p className="text-sm font-semibold uppercase tracking-[.18em] text-amber-400">{course.title}</p><h1 className="mt-3 text-3xl font-bold">{lesson.title}</h1><div className="mt-7 aspect-video overflow-hidden rounded-2xl border border-white/10 bg-[#0c1b2e]">{lesson.vimeo_video_id ? <iframe className="size-full" src={`https://player.vimeo.com/video/${lesson.vimeo_video_id}`} allow="autoplay; fullscreen; picture-in-picture" allowFullScreen title={lesson.title} /> : <div className="grid size-full place-items-center text-center"><div><Video className="mx-auto size-10 text-amber-400" /><p className="mt-4 font-medium">Vimeo video not connected yet</p><p className="mt-1 text-sm text-slate-400">Add the Vimeo video ID to this lesson in Supabase.</p></div></div>}</div><p className="mt-6 max-w-3xl leading-7 text-slate-300">{lesson.description ?? 'Complete this lesson, then mark it as finished to update your learning progress.'}</p><button onClick={completeLesson} disabled={completed.has(lesson.id) || saving} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-amber-400 px-5 py-3 font-semibold text-[#07111f] disabled:cursor-not-allowed disabled:opacity-60">{completed.has(lesson.id) ? <CheckCircle2 className="size-5" /> : <Play className="size-5" />}{completed.has(lesson.id) ? 'Lesson completed' : saving ? 'Saving progress…' : 'Mark as complete'}</button></section><aside className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><h2 className="px-2 py-3 font-semibold">Course lessons</h2><div className="space-y-1">{lessons.map((item, index) => <button key={item.id} onClick={() => setActiveLessonId(item.id)} className={`flex w-full items-center gap-3 rounded-xl p-3 text-left text-sm transition ${item.id === lesson.id ? 'bg-amber-400/15 text-white' : 'text-slate-300 hover:bg-white/5'}`}>{completed.has(item.id) ? <CheckCircle2 className="size-5 shrink-0 text-emerald-400" /> : <Circle className="size-5 shrink-0 text-slate-500" />}<span className="min-w-0"><span className="block text-xs text-slate-500">Lesson {index + 1}</span><span className="block truncate">{item.title}</span></span></button>)}</div></aside></div></main>;
}
