import Link from 'next/link';
import { CheckCircle2, PlayCircle, ArrowRight } from 'lucide-react';
import { createClient } from '@/lib/supabase/server';

export default async function RecordsPreview({ userId }: { userId?: string }) {
  if (!userId) return <section className="border-y border-blue-100 bg-blue-50 px-6 py-12"><div className="mx-auto max-w-7xl text-center"><h2 className="text-2xl font-bold text-[#09213f]">Your records. Your growth.</h2><p className="mt-2 text-slate-600">Sign in to track your learning progress.</p><Link href="/login" className="mt-5 inline-flex rounded-xl bg-[#00b8fe] px-5 py-3 font-semibold text-white">Sign in to continue</Link></div></section>;
  const supabase = await createClient(); const { data: courses } = await supabase.from('courses').select('id,title,lessons(id)').eq('published', true); const { data: progress } = await supabase.from('student_progress').select('lesson_id').eq('student_id', userId).eq('completed', true); const total = (courses ?? []).reduce((sum, course) => sum + (course.lessons?.length ?? 0), 0); const completed = (progress ?? []).length; const percent = total ? Math.round((completed / total) * 100) : 0;
  return <section className="border-y border-blue-100 bg-blue-50 px-6 py-16 lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[1fr_1fr] lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-[#0d62c7]">Live learning record</p><h2 className="mt-3 text-3xl font-bold text-[#09213f]">Your records. Your growth.</h2><p className="mt-4 max-w-lg leading-7 text-slate-600">Your progress is connected to your lessons and updates automatically whenever you complete a video.</p><Link href="/dashboard" className="mt-6 inline-flex items-center gap-2 font-semibold text-[#0d62c7]">Open dashboard <ArrowRight className="size-4" /></Link></div><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl bg-white p-5 shadow-sm"><PlayCircle className="size-6 text-[#00b8fe]" /><p className="mt-5 text-3xl font-bold text-[#09213f]">{total}</p><p className="text-sm text-slate-500">Video lessons</p></div><div className="rounded-2xl bg-white p-5 shadow-sm"><CheckCircle2 className="size-6 text-emerald-500" /><p className="mt-5 text-3xl font-bold text-[#09213f]">{completed}</p><p className="text-sm text-slate-500">Completed</p></div><div className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-3xl font-bold text-[#09213f]">{percent}%</p><p className="mt-2 text-sm text-slate-500">Overall progress</p><div className="mt-4 h-2 rounded-full bg-blue-100"><div className="h-full rounded-full bg-[#00b8fe]" style={{ width: `${percent}%` }} /></div></div></div></div></section>;
}
