'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { CheckCircle2, Circle, Video } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';

type Lesson = { id: string; title: string; description: string | null; vdocipher_video_id: string | null; lesson_order: number; duration_seconds: number | null };

export default function VdoCipherLessonPlayer({ course, lessons, completedLessonIds }: { course: { title: string; description: string | null; level: string }; lessons: Lesson[]; completedLessonIds: string[] }) {
  const [activeId, setActiveId] = useState(lessons[0]?.id ?? ''); const [playerUrl, setPlayerUrl] = useState(''); const [completed, setCompleted] = useState(new Set(completedLessonIds)); const [saving, setSaving] = useState(false); const lesson = lessons.find((item) => item.id === activeId);
  useEffect(() => { let cancelled = false; setPlayerUrl(''); if (!lesson?.vdocipher_video_id) return; fetch('/api/vdocipher/otp', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ videoId: lesson.vdocipher_video_id }) }).then((response) => response.json()).then((data: { otp?: string; playbackInfo?: string; error?: string }) => { if (!cancelled && data.otp && data.playbackInfo) setPlayerUrl(`https://player.vdocipher.com/v2/?otp=${data.otp}&playbackInfo=${data.playbackInfo}`); }).catch(() => undefined); return () => { cancelled = true; }; }, [lesson]);
  async function markComplete() { if (!lesson) return; setSaving(true); const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (user) { await supabase.from('student_progress').upsert({ student_id: user.id, lesson_id: lesson.id, completed: true, watched_seconds: lesson.duration_seconds ?? 0 }, { onConflict: 'student_id,lesson_id' }); await fetch('/api/audit/event', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'LESSON_COMPLETED', targetType: 'lesson', targetId: lesson.id, details: { lessonTitle: lesson.title, courseTitle: course.title } }) }); setCompleted((current) => new Set([...current, lesson.id])); } setSaving(false); }
  if (!lesson) return <main className="grid min-h-screen place-items-center bg-[#07111f] text-white"><p>No lessons added yet.</p></main>;
  return <main className="min-h-screen bg-[#07111f] text-white"><header className="border-b border-white/10 px-6 py-5"><div className="mx-auto flex max-w-7xl items-center justify-between"><Link href="/dashboard" className="text-sm text-amber-400">← Dashboard</Link><span className="text-sm text-slate-400">{course.level}</span></div></header><div className="mx-auto grid max-w-7xl gap-8 px-6 py-10 lg:grid-cols-[1fr_340px]"><section><p className="text-sm font-semibold uppercase tracking-[.18em] text-amber-400">{course.title}</p><h1 className="mt-3 text-3xl font-bold">{lesson.title}</h1><div className="mt-7 aspect-video overflow-hidden rounded-2xl border border-white/10 bg-[#0c1b2e]">{playerUrl ? <iframe className="size-full" src={playerUrl} allow="encrypted-media; fullscreen" allowFullScreen title={lesson.title} /> : <div className="grid size-full place-items-center text-center"><div><Video className="mx-auto size-10 text-amber-400" /><p className="mt-4 font-medium">{lesson.vdocipher_video_id ? 'Loading secure video…' : 'Video not connected yet'}</p><p className="mt-1 text-sm text-slate-400">{lesson.vdocipher_video_id ? 'If this stays loading, check the VdoCipher API secret.' : 'Add the VdoCipher ID from the Admin page.'}</p></div></div>}</div><p className="mt-6 leading-7 text-slate-300">{lesson.description}</p><button onClick={markComplete} disabled={saving || completed.has(lesson.id)} className="mt-7 rounded-xl bg-amber-400 px-5 py-3 font-semibold text-[#07111f] disabled:opacity-60">{completed.has(lesson.id) ? 'Lesson completed' : saving ? 'Saving…' : 'Mark as complete'}</button></section><aside className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><h2 className="px-2 py-3 font-semibold">Lessons</h2>{lessons.map((item, index) => <button key={item.id} onClick={() => setActiveId(item.id)} className={`flex w-full items-center gap-3 rounded-xl p-3 text-left text-sm ${item.id === lesson.id ? 'bg-amber-400/15' : 'hover:bg-white/5'}`}>{completed.has(item.id) ? <CheckCircle2 className="size-5 text-emerald-400" /> : <Circle className="size-5 text-slate-500" />}Day {index + 1} — {item.title}</button>)}</aside></div></main>;
}
