'use client';

import { FormEvent, useState } from 'react';

type Student = { id: string; full_name: string | null; phone: string | null; created_at: string };

export default function StudentManager({ students }: { students: Student[] }) {
  const [items, setItems] = useState(students); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  async function request(method: string, body?: unknown, id?: string) { const response = await fetch(`/api/admin/students${id ? `?id=${id}` : ''}`, { method, headers: { 'Content-Type': 'application/json' }, body: body ? JSON.stringify(body) : undefined }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? 'Request failed.'); return data; }
  function generatePassword() { const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$'; const values = new Uint32Array(14); crypto.getRandomValues(values); return `Kfx!${Array.from(values, (value) => chars[value % chars.length]).join('')}a1`; }
  async function addStudent(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(''); const form = new FormData(event.currentTarget); try { const data = await request('POST', { email: form.get('email'), password: form.get('password'), fullName: form.get('fullName'), phone: form.get('phone') }); setItems((current) => [data.student, ...current]); setMessage(`Student account created. Temporary password: ${data.temporaryPassword}`); event.currentTarget.reset(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to create student.'); } setSaving(false); }
  async function editStudent(student: Student) { const fullName = window.prompt('Student name', student.full_name ?? ''); if (!fullName) return; const phone = window.prompt('Phone number', student.phone ?? '') ?? ''; const password = window.prompt('New password (leave empty to keep current password)') ?? ''; try { const data = await request('PATCH', { id: student.id, fullName, phone, password: password || undefined }); setItems((current) => current.map((item) => item.id === student.id ? data.student : item)); setMessage('Student details updated.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to update student.'); } }
  async function removeStudent(student: Student) { if (!window.confirm(`Delete ${student.full_name ?? 'this student'} permanently?`)) return; try { await request('DELETE', undefined, student.id); setItems((current) => current.filter((item) => item.id !== student.id)); setMessage('Student deleted.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to delete student.'); } }
  return <section className="mt-10 rounded-3xl border border-blue-100 bg-blue-50/50 p-6 text-[#09213f]"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#0d62c7]">Student management</p><h2 className="mt-2 text-2xl font-bold">Add and manage students</h2><p className="mt-2 text-sm text-slate-500">Super Admin generates a secure temporary password for each new account.</p></div><span className="rounded-full bg-white px-3 py-1 text-xs font-semibold text-slate-600">{items.length} students</span></div><form onSubmit={addStudent} className="mt-6 grid gap-3 sm:grid-cols-2"><input name="fullName" required placeholder="Student full name" className="rounded-xl border border-blue-200 bg-white px-4 py-3 text-sm" /><input name="email" required type="email" placeholder="Student email" className="rounded-xl border border-blue-200 bg-white px-4 py-3 text-sm" /><div className="flex gap-2"><input name="password" minLength={8} type="text" placeholder="Generated password" className="min-w-0 flex-1 rounded-xl border border-blue-200 bg-white px-4 py-3 text-sm" /><button type="button" onClick={(event) => { const input = event.currentTarget.previousElementSibling as HTMLInputElement; input.value = generatePassword(); }} className="rounded-xl bg-blue-100 px-3 text-xs font-bold text-[#0d62c7]">Generate</button></div><input name="phone" placeholder="Phone (optional)" className="rounded-xl border border-blue-200 bg-white px-4 py-3 text-sm" /><button disabled={saving} className="rounded-xl bg-[#00b8fe] px-5 py-3 text-sm font-bold text-white disabled:opacity-50 sm:col-span-2">{saving ? 'Creating…' : 'Create student account'}</button></form>{message && <p className="mt-4 rounded-xl bg-white p-3 text-sm text-slate-600">{message}</p>}<div className="mt-6 space-y-2">{items.map((student) => <div key={student.id} className="flex flex-col gap-3 rounded-xl bg-white px-4 py-3 text-sm sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{student.full_name ?? 'Student'}</p><p className="text-xs text-slate-500">{student.phone ?? 'No phone added'} · Joined {new Date(student.created_at).toLocaleDateString()}</p></div><div className="flex gap-2"><button onClick={() => void editStudent(student)} className="rounded-lg bg-blue-50 px-3 py-2 text-xs font-semibold text-[#0d62c7]">Edit / reset password</button><button onClick={() => void removeStudent(student)} className="rounded-lg bg-red-50 px-3 py-2 text-xs font-semibold text-red-600">Delete</button></div></div>)}</div></section>;
}
