'use client';
import { useState } from 'react';
import { supabaseBrowser } from '../../lib/supabase';
export default function ApplicationActions({ id, status }: { id: string; status: string }) {
  const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  async function act(action: 'approve' | 'reject') { if (!window.confirm(action === 'approve' ? 'Approve this student and generate access?' : 'Reject this application?')) return; setBusy(true); const { data:{session} } = await supabaseBrowser().auth.getSession(); const response = await fetch('/api/applications', { method: 'PATCH', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${session?.access_token ?? ''}` }, body: JSON.stringify({ id, action }) }); const data = await response.json(); setMessage(response.ok ? action === 'approve' ? `Approved · Password: ${data.temporaryPassword}${data.emailWarning ? ` · ${data.emailWarning}` : ' · Email sent.'}` : 'Application rejected.' : data.error); setBusy(false); }
  if (status !== 'pending') return <span className="rounded-full border border-slate-700 bg-slate-800/70 px-3 py-1 text-xs text-slate-400">Processed</span>;
  return <div className="flex flex-wrap items-center justify-end gap-2"><select disabled={busy} defaultValue="" onChange={(event) => { const action = event.target.value as 'approve' | 'reject'; if (action) void act(action); event.target.value = ''; }} className="rounded-xl border border-blue-300/50 bg-[#0b1b31] px-4 py-2 text-xs font-bold text-white outline-none shadow-lg shadow-blue-950/20 focus:border-blue-300"><option value="" disabled>Manage application</option><option value="approve">Approve & generate access</option><option value="reject">Reject application</option></select>{message && <span className="w-full rounded-lg border border-amber-300/20 bg-amber-300/10 px-3 py-2 text-xs text-amber-200">{message}</span>}</div>;
}
