import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { createClient as createSupabaseClient } from '@supabase/supabase-js';

export async function POST(request: NextRequest) {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).single(); if (profile?.role !== 'admin') return NextResponse.json({ error: 'Only admins can create student accounts.' }, { status: 403 });
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY; if (!serviceKey) return NextResponse.json({ error: 'SUPABASE_SERVICE_ROLE_KEY is not configured on the server.' }, { status: 500 });
  const body = await request.json() as { email?: string; password?: string; fullName?: string; phone?: string }; const generatedPassword = body.password || `Kfx!${crypto.randomUUID().replaceAll('-', '').slice(0, 12)}a1`; if (!body.email || !body.fullName || generatedPassword.length < 8) return NextResponse.json({ error: 'Name, email, and a valid password are required.' }, { status: 400 });
  const admin = createSupabaseClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, serviceKey, { auth: { autoRefreshToken: false, persistSession: false } }); const { data, error } = await admin.auth.admin.createUser({ email: body.email, password: generatedPassword, email_confirm: true, user_metadata: { full_name: body.fullName } }); if (error || !data.user) return NextResponse.json({ error: error?.message ?? 'Could not create user.' }, { status: 400 });
  const { data: student, error: profileError } = await admin.from('profiles').upsert({ id: data.user.id, full_name: body.fullName, phone: body.phone ?? null, role: 'student', approval_status: 'approved' }).select('id,full_name,phone,created_at').single(); if (profileError) return NextResponse.json({ error: profileError.message }, { status: 400 }); return NextResponse.json({ student, temporaryPassword: generatedPassword });
}

async function getAdmin() {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return { error: 'Unauthorized', status: 401 as const }; const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).single(); if (profile?.role !== 'admin') return { error: 'Only admins can manage students.', status: 403 as const }; const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY; if (!serviceKey) return { error: 'SUPABASE_SERVICE_ROLE_KEY is not configured.', status: 500 as const }; return { admin: createSupabaseClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, serviceKey, { auth: { autoRefreshToken: false, persistSession: false } }) };
}

export async function PATCH(request: NextRequest) { const auth = await getAdmin(); if ('error' in auth) return NextResponse.json({ error: auth.error }, { status: auth.status }); const body = await request.json() as { id?: string; fullName?: string; phone?: string; password?: string }; if (!body.id || !body.fullName) return NextResponse.json({ error: 'Student ID and name are required.' }, { status: 400 }); const { error } = await auth.admin.from('profiles').update({ full_name: body.fullName, phone: body.phone ?? null }).eq('id', body.id).eq('role', 'student'); if (error) return NextResponse.json({ error: error.message }, { status: 400 }); if (body.password) { if (body.password.length < 8) return NextResponse.json({ error: 'Password must be at least 8 characters.' }, { status: 400 }); const result = await auth.admin.auth.admin.updateUserById(body.id, { password: body.password }); if (result.error) return NextResponse.json({ error: result.error.message }, { status: 400 }); } const { data } = await auth.admin.from('profiles').select('id,full_name,phone,created_at').eq('id', body.id).single(); return NextResponse.json({ student: data }); }

export async function DELETE(request: NextRequest) { const auth = await getAdmin(); if ('error' in auth) return NextResponse.json({ error: auth.error }, { status: auth.status }); const id = new URL(request.url).searchParams.get('id'); if (!id) return NextResponse.json({ error: 'Student ID is required.' }, { status: 400 }); const { error } = await auth.admin.auth.admin.deleteUser(id); if (error) return NextResponse.json({ error: error.message }, { status: 400 }); return NextResponse.json({ success: true }); }
