'use client';

import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { createClient } from '@/lib/supabase/client';

export default function GoogleOnboardingPage() {
  const [fullName, setFullName] = useState(''); const [email, setEmail] = useState(''); const [whatsappNumber, setWhatsappNumber] = useState(''); const [badge, setBadge] = useState('1'); const [message, setMessage] = useState('Preparing your Google account…'); const [loading, setLoading] = useState(true);
  useEffect(() => { void (async () => { const client = createClient(); const code = new URLSearchParams(window.location.search).get('code'); if (code) { const { error } = await client.auth.exchangeCodeForSession(code); if (error) { setMessage('Google sign-in expired. Please return to login and try again.'); setLoading(false); return; } window.history.replaceState({}, '', '/google-onboarding'); } const { data: { user } } = await client.auth.getUser(); if (!user) { setMessage('Google sign-in could not be completed. Return to login and try again.'); setLoading(false); return; } const { data: profile } = await client.from('profiles').select('approval_status,role').eq('id', user.id).maybeSingle(); if (profile?.approval_status === 'approved') { const started = await fetch('/api/session/register', { method: 'POST' }); if (started.ok) { window.location.replace(profile.role === 'admin' ? '/super-admin' : '/dashboard'); return; } setMessage('Could not start your secure session. Please try again.'); setLoading(false); return; } if (profile?.approval_status === 'rejected') { await client.auth.signOut(); setMessage('Your application was not approved. Please contact support.'); setLoading(false); return; } setEmail(user.email ?? ''); setFullName(String(user.user_metadata?.full_name ?? user.user_metadata?.name ?? '')); setMessage(''); setLoading(false); })(); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setMessage(''); const response = await fetch('/api/google-onboarding', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ fullName, whatsappNumber, badge: Number(badge) }) }); const data = await response.json(); if (!response.ok) { setMessage(data.error ?? 'Could not submit your application.'); setLoading(false); return; } await createClient().auth.signOut(); setMessage('Application submitted. Your Google account will be able to access the LMS after Super Admin approval.'); setLoading(false); }
  return <main className="grid min-h-screen place-items-center bg-[#07111f] px-6 py-12 text-white"><section className="w-full max-w-xl rounded-3xl border border-white/10 bg-white/[.04] p-7 shadow-2xl sm:p-10"><Link href="/" className="text-sm text-amber-400">← Krish FX Swing Lab</Link><p className="mt-8 text-sm font-semibold uppercase tracking-[.18em] text-amber-400">Google account application</p><h1 className="mt-3 text-3xl font-bold">Complete your student details</h1><p className="mt-3 text-slate-400">Your Google sign-in is connected. Submit these details for Super Admin approval before accessing lessons.</p><form onSubmit={submit} className="mt-8 space-y-5"><label className="block text-sm font-medium">Full Name *<input required value={fullName} onChange={(event) => setFullName(event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3" /></label><label className="block text-sm font-medium">Google Email<input readOnly value={email} className="mt-2 w-full cursor-not-allowed rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-slate-400" /></label><label className="block text-sm font-medium">WhatsApp Number *<input required value={whatsappNumber} onChange={(event) => setWhatsappNumber(event.target.value)} placeholder="+94 71 123 4567" className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3" /></label><label className="block text-sm font-medium">Badge<select value={badge} onChange={(event) => setBadge(event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3"><option value="1">Badge 1</option><option value="2">Badge 2</option></select></label>{message && <p className="rounded-xl border border-amber-400/25 bg-amber-400/10 p-4 text-sm text-amber-100">{message}</p>}<button disabled={loading || !email} className="w-full rounded-xl bg-amber-400 py-3.5 font-semibold text-[#07111f] disabled:opacity-50">{loading ? 'Submitting…' : 'Submit for approval'}</button></form></section></main>;
}
