'use client';

import { useMemo, useState } from 'react';
import { supabaseBrowser } from '../../lib/supabase';

type Course = { id: string; title: string };
type Section = { id: string; course_id: string; title: string; description: string | null; section_order: number };
type Lesson = { id: string; course_id: string; section_id: string | null; title: string; description: string | null; vdocipher_video_id: string | null; lesson_order: number };
const inputClass = 'rounded-xl border border-slate-700 bg-slate-950 px-3 py-3 text-white outline-none placeholder:text-slate-500 focus:border-cyan-400';

export default function ContentManager({ courses, lessons, sections: initialSections }: { courses: Course[]; lessons: Lesson[]; sections: Section[] }) {
  const [items, setItems] = useState(lessons); const [sections, setSections] = useState(initialSections); const [message, setMessage] = useState('');
  const [sectionForm, setSectionForm] = useState({ courseId: courses[0]?.id ?? '', title: '', description: '', order: String(initialSections.length + 1) });
  const [form, setForm] = useState({ courseId: courses[0]?.id ?? '', sectionId: '', title: '', description: '', videoId: '', order: String(items.length + 1) });
  const visibleSections = useMemo(() => sections.filter((item) => item.course_id === form.courseId).sort((a, b) => a.section_order - b.section_order), [sections, form.courseId]);
  const sectionsFor = (courseId: string) => sections.filter((item) => item.course_id === courseId).sort((a, b) => a.section_order - b.section_order);
  const call = async (path: string, method: string, body: unknown) => { const { data: { session } } = await supabaseBrowser().auth.getSession(); const response = await fetch(path, { method, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${session?.access_token ?? ''}` }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Request failed.'); return data; };
  async function addSection(event: React.FormEvent) { event.preventDefault(); try { const data = await call('/api/content/sections', 'POST', sectionForm); setSections((current) => [...current, data.section]); setSectionForm((current) => ({ ...current, title: '', description: '', order: String(sections.length + 2) })); setMessage('Sub-course created. You can now add lessons/videos inside it.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not create sub-course.'); } }
  async function deleteSection(id: string) { if (!confirm('Delete this sub-course? Lessons are kept but become unassigned.')) return; try { await call('/api/content/sections', 'DELETE', { id }); setSections((current) => current.filter((item) => item.id !== id)); setItems((current) => current.map((item) => item.section_id === id ? { ...item, section_id: null } : item)); setMessage('Sub-course deleted.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not delete sub-course.'); } }
  async function addLesson(event: React.FormEvent) { event.preventDefault(); try { const data = await call('/api/content/lessons', 'POST', form); setItems((current) => [...current, data.lesson]); setForm((current) => ({ ...current, title: '', description: '', videoId: '', order: String(items.length + 2) })); setMessage('Lesson/video added.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not add lesson.'); } }
  async function saveLesson(item: Lesson) { try { await call('/api/content/lessons', 'PATCH', { id: item.id, courseId: item.course_id, sectionId: item.section_id, title: item.title, description: item.description, videoId: item.vdocipher_video_id, order: item.lesson_order }); setMessage('Lesson saved.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not save lesson.'); } }
  async function removeLesson(id: string) { if (!confirm('Delete this lesson permanently?')) return; try { await call('/api/content/lessons', 'DELETE', { id }); setItems((current) => current.filter((item) => item.id !== id)); setMessage('Lesson deleted.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not delete lesson.'); } }
  const update = <K extends keyof Lesson>(id: string, key: K, value: Lesson[K]) => setItems((current) => current.map((item) => item.id === id ? { ...item, [key]: value } : item));
  return <div className="mt-8 space-y-8">
    <section className="rounded-2xl border border-cyan-400/20 bg-cyan-400/[.06] p-5"><p className="text-xs font-bold uppercase tracking-[.18em] text-cyan-300">Step 1</p><h2 className="mt-1 text-xl font-bold text-white">Create a sub-course</h2><p className="mt-1 text-sm text-slate-400">Example: Market Structure, Risk Management, or Trading Psychology.</p><form onSubmit={addSection} className="mt-5 grid gap-3 md:grid-cols-2"><select required value={sectionForm.courseId} onChange={(event) => setSectionForm({ ...sectionForm, courseId: event.target.value })} className={inputClass}>{courses.map((course) => <option key={course.id} value={course.id}>{course.title}</option>)}</select><input required value={sectionForm.title} onChange={(event) => setSectionForm({ ...sectionForm, title: event.target.value })} placeholder="Sub-course name" className={inputClass}/><textarea value={sectionForm.description} onChange={(event) => setSectionForm({ ...sectionForm, description: event.target.value })} placeholder="Short description (optional)" className={`${inputClass} md:col-span-2`}/><input type="number" min="1" value={sectionForm.order} onChange={(event) => setSectionForm({ ...sectionForm, order: event.target.value })} className={inputClass}/><button className="rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950">Create sub-course</button></form><div className="mt-5 grid gap-2 md:grid-cols-2">{sections.map((section) => <div key={section.id} className="flex items-center justify-between rounded-xl border border-slate-700 bg-slate-950/80 p-3"><span><span className="font-semibold text-white">{section.title}</span><span className="ml-2 text-xs text-slate-400">#{section.section_order}</span></span><button type="button" onClick={() => void deleteSection(section.id)} className="text-sm font-semibold text-rose-300">Delete</button></div>)}</div></section>
    <section className="rounded-2xl border border-blue-400/20 bg-blue-500/[.08] p-5"><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-300">Step 2</p><h2 className="mt-1 text-xl font-bold text-white">Add lesson / VdoCipher video</h2><form onSubmit={addLesson} className="mt-5 grid gap-3 md:grid-cols-2"><select value={form.courseId} onChange={(event) => setForm({ ...form, courseId: event.target.value, sectionId: '' })} required className={inputClass}><option value="">Select course</option>{courses.map((course) => <option key={course.id} value={course.id}>{course.title}</option>)}</select><select value={form.sectionId} onChange={(event) => setForm({ ...form, sectionId: event.target.value })} className={inputClass}><option value="">No sub-course (unassigned)</option>{visibleSections.map((section) => <option key={section.id} value={section.id}>{section.title}</option>)}</select><input required placeholder="Lesson / video name" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} className={inputClass}/><input placeholder="VdoCipher Video ID" value={form.videoId} onChange={(event) => setForm({ ...form, videoId: event.target.value })} className={inputClass}/><input type="number" min="1" placeholder="Lesson order" value={form.order} onChange={(event) => setForm({ ...form, order: event.target.value })} className={inputClass}/><textarea placeholder="Description" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} className={inputClass}/><button className="rounded-xl bg-blue-600 px-5 py-3 font-bold text-white md:col-span-2">Add lesson & video</button></form></section>
    {message && <p className="rounded-xl border border-amber-300/20 bg-amber-300/10 px-4 py-3 text-sm text-amber-200">{message}</p>}
    <section><h2 className="text-xl font-bold text-white">All lessons</h2><div className="mt-4 space-y-4">{[...items].sort((a, b) => a.lesson_order - b.lesson_order).map((item) => <div key={item.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="grid gap-3 md:grid-cols-2"><input value={item.title} onChange={(event) => update(item.id, 'title', event.target.value)} className={inputClass}/><input value={item.vdocipher_video_id ?? ''} onChange={(event) => update(item.id, 'vdocipher_video_id', event.target.value || null)} placeholder="VdoCipher Video ID" className={inputClass}/><select value={item.section_id ?? ''} onChange={(event) => update(item.id, 'section_id', event.target.value || null)} className={inputClass}><option value="">No sub-course (unassigned)</option>{sectionsFor(item.course_id).map((section) => <option key={section.id} value={section.id}>{section.title}</option>)}</select><input type="number" min="1" value={item.lesson_order} onChange={(event) => update(item.id, 'lesson_order', Number(event.target.value))} className={inputClass}/><textarea value={item.description ?? ''} onChange={(event) => update(item.id, 'description', event.target.value || null)} placeholder="Description" className={`${inputClass} md:col-span-2`}/></div><div className="mt-3 flex gap-3"><button type="button" onClick={() => void saveLesson(item)} className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white">Save changes</button><button type="button" onClick={() => void removeLesson(item.id)} className="rounded-xl border border-rose-400/40 px-4 py-2 text-sm font-bold text-rose-300">Delete</button></div></div>)}</div></section>
  </div>;
}
