'use client';
import { useState } from 'react';
import { supabaseBrowser } from '../../lib/supabase';
type Course={id:string;title:string}; type Lesson={id:string;title:string;description:string|null;vdocipher_video_id:string|null;lesson_order:number};
export default function ContentManager({courses,lessons}:{courses:Course[];lessons:Lesson[]}) {
 const [items,setItems]=useState(lessons); const [form,setForm]=useState({courseId:courses[0]?.id??'',title:'',description:'',videoId:'',order:String(items.length+1)}); const [message,setMessage]=useState('');
 const api=async(method:string,body:unknown)=>{const { data:{session} }=await supabaseBrowser().auth.getSession();const r=await fetch('/api/content/lessons',{method,headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token??''}`},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);return d};
 async function add(e:React.FormEvent){e.preventDefault();try{const d=await api('POST',form);setItems([...items,d.lesson]);setForm({...form,title:'',description:'',videoId:'',order:String(items.length+2)});setMessage('Lesson added.')}catch(e){setMessage(e instanceof Error?e.message:'Error');}}
 async function save(item:Lesson){try{await api('PATCH',{id:item.id,title:item.title,description:item.description,videoId:item.vdocipher_video_id,order:item.lesson_order});setMessage('Changes saved.')}catch(e){setMessage(e instanceof Error?e.message:'Error');}}
 async function remove(id:string){if(!confirm('Delete this lesson permanently?'))return;try{await api('DELETE',{id});setItems(items.filter(x=>x.id!==id));setMessage('Lesson deleted.')}catch(e){setMessage(e instanceof Error?e.message:'Error');}}
 const update=(id:string,key:keyof Lesson,value:string)=>setItems(items.map(x=>x.id===id?{...x,[key]:key==='lesson_order'?Number(value):value}:x));
 return <><form onSubmit={add} className="mt-6 grid gap-3 rounded-2xl border border-blue-400/20 bg-blue-500/10 p-5 md:grid-cols-2"><select value={form.courseId} onChange={e=>setForm({...form,courseId:e.target.value})} required className="rounded-xl p-3"><option value="">Select course</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select><input required placeholder="Lesson name / Video name" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="rounded-xl p-3" /><input placeholder="VdoCipher Video ID" value={form.videoId} onChange={e=>setForm({...form,videoId:e.target.value})} className="rounded-xl p-3" /><input type="number" min="1" placeholder="Lesson order" value={form.order} onChange={e=>setForm({...form,order:e.target.value})} className="rounded-xl p-3" /><textarea placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="rounded-xl p-3 md:col-span-2" /><button className="rounded-xl bg-blue-600 px-5 py-3 font-bold text-white md:col-span-2">Add lesson & video</button></form>{message&&<p className="mt-4 text-sm text-amber-300">{message}</p>}<div className="mt-6 space-y-4">{items.map(item=><div key={item.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="grid gap-3 md:grid-cols-2"><input value={item.title} onChange={e=>update(item.id,'title',e.target.value)} className="rounded-xl p-3" /><input value={item.vdocipher_video_id??''} onChange={e=>update(item.id,'vdocipher_video_id',e.target.value)} placeholder="VdoCipher Video ID" className="rounded-xl p-3" /><textarea value={item.description??''} onChange={e=>update(item.id,'description',e.target.value)} placeholder="Description" className="rounded-xl p-3 md:col-span-2" /><input type="number" min="1" value={item.lesson_order} onChange={e=>update(item.id,'lesson_order',e.target.value)} className="rounded-xl p-3" /></div><div className="mt-3 flex gap-3"><button onClick={()=>void save(item)} className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white">Save changes</button><button onClick={()=>void remove(item.id)} className="rounded-xl border border-red-400/40 px-4 py-2 text-sm font-bold text-red-300">Delete</button></div></div>)}</div></>;
}
