'use client';
import { FormEvent, useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

export default function ChangePasswordPage() {
  const [email, setEmail] = useState(''); const [current, setCurrent] = useState(''); const [next, setNext] = useState(''); const [confirm, setConfirm] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { createClient().auth.getUser().then(({ data: { user } }) => setEmail(user?.email ?? '')); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setMessage(''); if (next.length < 8) { setMessage('New password must be at least 8 characters.'); return; } if (next !== confirm) { setMessage('New passwords do not match.'); return; } setBusy(true); const client = createClient(); const verified = await client.auth.signInWithPassword({ email, password: current }); if (verified.error) { setBusy(false); setMessage('Current password is incorrect.'); return; } const { error } = await client.auth.updateUser({ password: next, data: { must_change_password: false } }); if (error) { setBusy(false); setMessage(error.message); return; } await fetch('/api/audit/event', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'PASSWORD_CHANGED', targetType: 'student_password', targetId: email, details: { source: 'forced_first_login' } }) }); await client.auth.signOut(); window.location.replace('/login?reason=password-changed'); }
  return <main className="grid min-h-screen place-items-center bg-[#07111f] px-5 py-10 text-white"><form onSubmit={submit} className="w-full max-w-md rounded-3xl border border-cyan-400/20 bg-white/[.04] p-8 shadow-2xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">Security required</p><h1 className="mt-3 text-3xl font-bold">Change your password</h1><p className="mt-3 leading-7 text-slate-400">For your security, change the temporary password before continuing.</p><p className="mt-5 rounded-xl bg-white/5 px-4 py-3 text-sm text-slate-300">Account: {email || 'Loading…'}</p><label className="mt-6 block text-sm font-semibold">Current temporary password<input required type="password" autoComplete="current-password" value={current} onChange={e => setCurrent(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3" /></label><label className="mt-4 block text-sm font-semibold">New password<input required minLength={8} type="password" autoComplete="new-password" value={next} onChange={e => setNext(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3" /></label><label className="mt-4 block text-sm font-semibold">Confirm new password<input required minLength={8} type="password" autoComplete="new-password" value={confirm} onChange={e => setConfirm(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3" /></label>{message && <p className="mt-4 rounded-xl border border-rose-300/20 bg-rose-300/10 p-3 text-sm text-rose-200">{message}</p>}<button disabled={busy} className="mt-6 w-full rounded-xl bg-cyan-400 py-3.5 font-bold text-slate-950 disabled:opacity-60">{busy ? 'Updating password…' : 'Save new password'}</button></form></main>;
}