'use client';

import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { createClient } from '@/lib/supabase/client';

export default function LoginPage() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function login(event: FormEvent) { event.preventDefault(); setLoading(true); setError(''); const client = createClient(); const { data, error: authError } = await client.auth.signInWithPassword({ email, password }); if (authError) setError(authError.message); else if (data.user) { const { data: profile } = await client.from('profiles').select('approval_status,role').eq('id', data.user.id).single(); if (profile?.approval_status === 'pending') { await client.auth.signOut(); setError('Your application is pending admin approval.'); } else if (profile?.approval_status === 'rejected') { await client.auth.signOut(); setError('Your application was not approved. Please contact support.'); } else { const sessionResponse = await fetch('/api/session/register', { method: 'POST' }); if (!sessionResponse.ok) { await client.auth.signOut(); setError('Could not start a secure session.'); } else window.location.href = profile?.role === 'admin' ? '/super-admin' : '/dashboard'; } } setLoading(false); }
  return <main className="grid min-h-screen place-items-center bg-[#07111f] px-6 text-white"><form onSubmit={login} className="w-full max-w-md rounded-3xl border border-white/10 bg-white/[.04] p-8"><Link href="/" className="text-sm text-amber-400">← Krish FX Swing Lab</Link><h1 className="mt-8 text-3xl font-bold">Welcome back</h1><p className="mt-2 text-slate-400">Sign in to continue learning.</p><label className="mt-8 block text-sm">Email<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none focus:border-amber-400" /></label><label className="mt-4 block text-sm">Password<input required type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none focus:border-amber-400" /></label>{error && <p className="mt-4 text-sm text-red-400">{error}</p>}<button disabled={loading} className="mt-6 w-full rounded-xl bg-amber-400 py-3 font-semibold text-[#07111f] disabled:opacity-50">{loading ? 'Signing in…' : 'Sign in'}</button><p className="mt-6 text-center text-sm text-slate-400">New student? <Link href="/signup" className="text-amber-400">Create account</Link></p></form></main>;
}
