'use client';
import { type FormEvent, useState } from 'react';
import Link from 'next/link';
import TurnstileWidget from '@/components/auth/turnstile-widget';
export default function SignupPage() {
 const [fullName,setFullName]=useState(''); const [email,setEmail]=useState(''); const [whatsappNumber,setWhatsappNumber]=useState(''); const [badge,setBadge]=useState('1'); const [turnstileToken,setTurnstileToken]=useState(''); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();if(!turnstileToken){setMessage('Please complete the security check first.');return;}setLoading(true);const r=await fetch('/api/student-applications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fullName,email,whatsappNumber,badge:Number(badge),turnstileToken})});const d=await r.json();setMessage(r.ok?'Application submitted. The Super Admin will review your details and email your login access after approval.':d.error);setLoading(false);}
 return <main className="min-h-screen bg-[#07111f] px-6 py-12 text-white"><div className="mx-auto max-w-xl"><Link href="/" className="text-sm text-amber-400">← Krish FX Swing Lab</Link><div className="mt-12 rounded-[2rem] border border-white/10 bg-white/[.04] p-7 shadow-2xl sm:p-10"><p className="text-sm font-semibold uppercase tracking-[.18em] text-amber-400">Create Account</p><h1 className="mt-3 text-3xl font-bold">Start your learning journey</h1><p className="mt-4 text-slate-400">Submit your details first. Password and course access are created after Super Admin approval.</p><form onSubmit={submit} className="mt-8 space-y-5"><label className="block text-sm font-medium">Name *<input required maxLength={100} value={fullName} onChange={e=>setFullName(e.target.value)} placeholder="Kasun Perera" className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3" /></label><label className="block text-sm font-medium">Email Address *<input required type="email" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} placeholder="your.email@example.com" className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3" /></label><label className="block text-sm font-medium">WhatsApp Number *<input required maxLength={25} value={whatsappNumber} onChange={e=>setWhatsappNumber(e.target.value)} placeholder="+94 71 123 4567" className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3" /></label><label className="block text-sm font-medium">Badge<select value={badge} onChange={e=>setBadge(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3"><option value="1">Badge 1</option><option value="2">Badge 2</option><option value="3">Badge 3</option></select></label><TurnstileWidget onToken={setTurnstileToken}/>{message&&<p className="rounded-xl bg-white/10 p-4 text-sm text-amber-200">{message}</p>}<button disabled={loading||!turnstileToken} className="w-full rounded-xl bg-amber-400 py-3.5 font-semibold text-[#07111f] disabled:opacity-50">{loading?'Submitting…':'Submit application'}</button></form><p className="mt-6 text-center text-sm text-slate-400">Already approved? <Link href="/login" className="text-amber-400">Sign in</Link></p></div></div></main>;
}
