'use client';
import { useState } from 'react';
import { supabaseBrowser } from '../../lib/supabase';
type PermissionKey = 'manage_students' | 'manage_content' | 'manage_applications' | 'view_reports';
type Admin = { id: string; full_name: string | null; email: string | null; permissions: Record<PermissionKey, boolean> };
const labels: Record<PermissionKey, string> = { manage_students: 'Manage students & passwords', manage_content: 'Manage lessons & VdoCipher videos', manage_applications: 'Approve / reject applications', view_reports: 'View LMS audit reports' };
export default function AdminManager({ admins }: { admins: Admin[] }) {
  const [items, setItems] = useState(admins); const [form, setForm] = useState({ fullName: '', email: '', password: '', permissions: { manage_students: false, manage_content: false, manage_applications: false, view_reports: true } }); const [message, setMessage] = useState('');
  async function request(method: string, body: unknown) { const { data: { session } } = await supabaseBrowser().auth.getSession(); const response = await fetch('/api/admins', { method, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${session?.access_token ?? ''}` }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); return data; }
  async function create(event: React.FormEvent) { event.preventDefault(); try { const data = await request('POST', form); setItems([{ id: data.admin.id, full_name: data.admin.fullName, email: data.admin.email, permissions: form.permissions }, ...items]); setForm({ fullName: '', email: '', password: '', permissions: { manage_students: false, manage_content: false, manage_applications: false, view_reports: true } }); setMessage('Main Admin account created. Give them the email and password securely.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Error'); } }
  async function remove(item: Admin) { if (!window.confirm('Delete this Main Admin account?')) return; try { await request('DELETE', { id: item.id }); setItems(items.filter(current => current.id !== item.id)); setMessage('Main Admin deleted.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Error'); } }
  async function save(item: Admin) { try { await request('PATCH', { id: item.id, permissions: item.permissions }); setMessage('Permissions updated.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Error'); } }
  function toggle(target: { permissions: Record<PermissionKey, boolean> }, key: PermissionKey) { target.permissions[key] = !target.permissions[key]; setItems([...items]); setForm({ ...form, permissions: { ...target.permissions } }); }
  const controls = (permissions: Record<PermissionKey, boolean>, onToggle: (key: PermissionKey) => void) => <div className="grid gap-2 sm:grid-cols-2">{(Object.keys(labels) as PermissionKey[]).map(key => <label key={key} className="flex items-center gap-2 rounded-xl border border-slate-700 bg-slate-950/60 p-3 text-sm"><input type="checkbox" checked={permissions[key]} onChange={() => onToggle(key)} />{labels[key]}</label>)}</div>;
  return <><form onSubmit={create} className="mt-8 space-y-4 rounded-3xl border border-blue-400/25 bg-blue-500/10 p-6"><h2 className="text-xl font-bold">Create Main Admin</h2><div className="grid gap-3 md:grid-cols-3"><input required value={form.fullName} onChange={e => setForm({ ...form, fullName: e.target.value })} placeholder="Full name" className="rounded-xl p-3 text-slate-900" /><input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="Admin email" className="rounded-xl p-3 text-slate-900" /><input required minLength={8} type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} placeholder="Set temporary password" className="rounded-xl p-3 text-slate-900" /></div>{controls(form.permissions, key => setForm({ ...form, permissions: { ...form.permissions, [key]: !form.permissions[key] } }))}<button className="rounded-xl bg-blue-600 px-5 py-3 font-bold text-white">Create Main Admin</button></form>{message && <p className="mt-4 rounded-xl border border-amber-300/20 bg-amber-300/10 p-3 text-sm text-amber-200">{message}</p>}<div className="mt-8 space-y-4">{items.map(item => <section key={item.id} className="rounded-3xl border border-slate-800 bg-slate-900 p-6"><p className="font-bold">{item.full_name ?? 'Main Admin'}</p><p className="mt-1 text-sm text-slate-400">{item.email} · <span className="font-mono text-xs">{item.id}</span></p><div className="mt-4">{controls(item.permissions, key => toggle(item, key))}</div><div className="mt-4 flex flex-wrap gap-2"><button onClick={() => void save(item)} className="rounded-xl border border-blue-400/50 px-4 py-2 text-sm font-bold text-blue-300">Save permissions</button><button onClick={() => void remove(item)} className="rounded-xl border border-red-400/50 px-4 py-2 text-sm font-bold text-red-300">Delete admin</button></div></section>)}{!items.length && <p className="text-slate-400">No Main Admin accounts yet.</p>}</div></>;
}
